server:
  port : 8082
  servlet:
    context-path: /


spring:
  datasource:
    username: root
    password: y3377203
    url: jdbc:mysql://localhost:3306/yewencong?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: ye-eureka

eureka:
  instance:
    hostname : eureka2
  client:
    registerWithEureka : true
    fetchRegistry : true
    serviceUrl:
      defaultZone : http://eureka1:8081/eureka/,http://eureka2:8082/eureka/
